apiVersion: v1
kind: Pod 
metadata: 
  name: day2
  labels: 
    run: day2
    service: webservice
spec: 
  containers: 
  - name: container1
    image: nginx 
    volumeMounts:
      - mountPath: /giropops1
        name: primeiro-emptydir
    resources: 
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  - name: container2
    image: python
    command:
      - "sleep"
      - "3600"
    volumeMounts:
      - mountPath: /giropops2
        name: segundo-emptydir
    resources: 
      limits:
        cpu: "1"
        memory: "64Mi"
      requests:
        cpu: "0.3"
        memory: "32Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always 
  volumes:
    - name: primeiro-emptydir
      emptyDir:
        sizeLimit: 256Mi
    - name: segundo-emptydir
      emptyDir:
        sizeLimit: 256Mi