apiVersion: v1
kind: PersistentVolume
metadata:
  name: primeiro-pv
  labels:
    storage: nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /opt/nfs
    server: 10.20.60.200
    readOnly: false
